 name: CI
 
 on: [push, pull_request]
 
 jobs:
   build_for_linux_and_operational_test:
     runs-on: ubuntu-18.04
     steps:
     - uses: actions/checkout@v2
     - name: Build
       run: |
         set -eux
         docker run --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:1.46.0 sh -c 'sudo chown -R rust:rust . && cargo build --release'
         sudo chown -R $USER:$USER .
     - name: Archive
       run: |
         set -eux
         mkdir patient-manage-x86-64-linux
         cp target/x86_64-unknown-linux-musl/release/patient-manage patient-manage-x86-64-linux
         zip -r patient-manage-x86-64-linux.zip patient-manage-x86-64-linux
         tar czf patient-manage-x86-64-linux.tar.gz patient-manage-x86-64-linux
     - name: Upload Linux executables as artifacts
       uses: actions/upload-artifact@v2
       with:
         name: ${{ github.sha }}-linux-artifacts
         path: patient-manage-x86-64-linux.*
 
   build_for_mac:
     runs-on: macOS-10.15
     steps:
     - uses: actions/checkout@v2
     - run: cargo build --release
     - name: Archive
       run: |
         set -eux
         mkdir patient-manage-x86-64-apple-darwin
         cp target/release/patient-manage patient-manage-x86-64-apple-darwin
         zip -r patient-manage-x86-64-apple-darwin.zip patient-manage-x86-64-apple-darwin
         tar czf patient-manage-x86-64-apple-darwin.tar.gz patient-manage-x86-64-apple-darwin
     - name: Upload macOS executables as artifacts
       uses: actions/upload-artifact@v2
       with:
         name: ${{ github.sha }}-mac-artifacts
         path: patient-manage-x86-64-apple-darwin.*
 
   release_if_tag_exits:
     needs: [build_for_linux_and_operational_test, build_for_mac]
     runs-on: ubuntu-18.04
     steps:
     - name: Extract tag name
       shell: bash
       run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
       id: extract_tag
     - uses: actions/checkout@v2
     - name: Download the artifact (Linux)
       uses: actions/download-artifact@v2
       with:
         name: ${{ github.sha }}-linux-artifacts
     - name: Download the artifact (macOS)
       uses: actions/download-artifact@v2
       with:
         name: ${{ github.sha }}-mac-artifacts
     - name: Release
       if: contains(github.ref, 'refs/tags/')
       run: |
         set -eux
         hub release create \
           -a patient-manage-x86-64-linux.tar.gz \
           -a patient-manage-x86-64-linux.zip \
           -a patient-manage-x86-64-apple-darwin.tar.gz \
           -a patient-manage-x86-64-apple-darwin.zip \
           -m "Release ${{ steps.extract_tag.outputs.tag }}" ${{ steps.extract_tag.outputs.tag }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
